### PR TITLE
Updated README.md and added Issue Templates

### PR DESCRIPTION
**Pull request by mmattbtw**
Added things such at Issue Templates for Bug Requests and Feature Requests.
Updated the README.md to remove the large Top.gg badge, and instead use the smaller badges, as well as adding a section for how to support Arctic on Patreon, and other GitHub badges.

### CODE REVIEW

**Comment by mmattbtw** [comment]
Added more things such as check boxes for the Future Things list, and a hyperlink for the title https://github.com/X-Corporation/Arctic/pull/1/commits/3433279f92bc63d885d3d01c3b1bf5209148dd36

**Comment by mmattbtw** [comment]
Added a Discord Server badge for the support server https://github.com/X-Corporation/Arctic/pull/1/commits/306882fb1e32aede44d33c4fe575cfc2dbcae23f

**Comment by mmattbtw** [comment]
sorry for commit spam, i was just looking between different looks haha

**Comment by x-daniel-17** [comment]
ok very kewl I merge now

**Comment by mmattbtw** [comment]
LETS GOOOOOO

**Pull request merged**
